name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          CMOCKA_MESSAGE_OUTPUT: xml
          CMOCKA_XML_FILE: ../bin/TEST-cmocka.xml
        run: |
          mkdir bin
          ./docker-make all
          export VERSION=$(cat ./bin/version.txt)
      - name: Report test results
        uses: ashley-taylor/junit-report-annotations-action@1.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Actions ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/mega-drive-midi-interface-${{ env.VERSION }}.bin
          asset_name: mega-drive-midi-interface-${{ env.VERSION }}.bin
          asset_content_type: application/octet-stream
