name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
            CMOCKA_MESSAGE_OUTPUT: xml
            CMOCKA_XML_FILE: ../bin/cmocka.xml
        run: |
          mkdir bin
          ./docker-make all
      - name: Report test results
        uses: ashley-taylor/junit-report-annotations-action@1.3
          if: always()
          with:
            access-token: ${{ secrets.GITHUB_TOKEN }}
